### ISSUE TITLE
API return 404 

### ISSUE THREAD

**Issue by vincent-the** [ZekeSnider/Jared#33] opened 2020-04-22 19:08 UTC
Hello i have started the current version (1.14) on a 10.15.4 in the GUI is both enabled. The api is also available on port 3000 but it returns an error code 404 on every request.

**Comment by ZekeSnider** [comment] 2020-04-22 21:58
Hi, could you post the request you are making?

**Comment by ZekeSnider** [comment] 2020-07-15 16:07
Closing since I can't reproduce it. Please re-open if you're still having the issue

**Closed by ZekeSnider** 2020-07-15 16:07 UTC
