### ISSUE TITLE
Several Commands Broken

### ISSUE THREAD

**Issue by gardinermichael** [ZekeSnider/Jared#27] opened 2019-07-10 17:49 UTC
Hey there! Love the idea. I'm having a couple issues running some basic commands.

```
/schedule,add,1,week,5,message
```
returns:

```
Send interval type must be a valid input (hour, day, week, month).
```
Secondly, running:

```
/help,schedule
```
Returns nothing

**Comment by ZekeSnider** [comment] 2019-12-29 06:13
Hi, apologies for the very late response. This is bad documentation, I think the issue is `week` must be capitalized to `Week` in your command. And for the `/help` issue it's a bit counter intuitive, buit you need to send `/help,/schedule`

**Comment by ZekeSnider** [comment] 2020-04-19 02:01
Closing this, feel free to reopen if you’re still having issues.

**Closed by ZekeSnider** 2020-04-19 02:01 UTC
